import type { Destination, TravelStyle } from './types';

// ── Destination Catalog ──────────────────────────────────────
// 50+ seeded destinations covering domestic India + international

export const DESTINATIONS: Destination[] = [
  // ────────── INDIA DOMESTIC ──────────────────────────────────
  {
    id: 'goa_in',
    slug: 'goa-india',
    city: 'Goa',
    country: 'India',
    countryCode: 'IN',
    region: 'South Asia',
    lat: 15.2993,
    lng: 74.1240,
    airportCodes: ['GOI'],
    tags: ['BEACH', 'NIGHTLIFE', 'RELAXATION', 'FOOD'],
    climateZone: 'TROPICAL',
    popularityScore: 9.2,
    description: 'India\'s beach paradise — golden sands, vibrant nightlife, Portuguese architecture and fresh seafood.',
    highlights: ['Baga Beach', 'Old Goa Churches', 'Dudhsagar Falls', 'Anjuna Flea Market'],
    imageUrl: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=800',
    costProfile: {
      style: 'BUDGET',
      foodDailyLow: 300, foodDailyMid: 600, foodDailyHigh: 1200,
      localTransitDaily: 200, activitiesDaily: 400,
      hotelNightLow: 800, hotelNightMid: 2000, hotelNightHigh: 5000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '01': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Perfect weather, peak season' },
      '02': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Excellent, slightly less crowded' },
      '03': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Warm and pleasant' },
      '04': { weatherScore: 7, crowdLevel: 'LOW', description: 'Hot, fewer tourists' },
      '05': { weatherScore: 4, crowdLevel: 'LOW', description: 'Pre-monsoon heat' },
      '06': { weatherScore: 3, crowdLevel: 'LOW', description: 'Monsoon season, heavy rain' },
      '07': { weatherScore: 3, crowdLevel: 'LOW', description: 'Heavy monsoon' },
      '08': { weatherScore: 4, crowdLevel: 'LOW', description: 'Monsoon tapering' },
      '09': { weatherScore: 5, crowdLevel: 'LOW', description: 'Late monsoon' },
      '10': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Pleasant, shoulder season' },
      '11': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Great weather, busier' },
      '12': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Festival season, peak crowds' },
    },
  },
  {
    id: 'manali_in',
    slug: 'manali-india',
    city: 'Manali',
    country: 'India',
    countryCode: 'IN',
    region: 'South Asia',
    lat: 32.2432,
    lng: 77.1892,
    airportCodes: ['KUU'],
    tags: ['MOUNTAINS', 'ADVENTURE', 'SNOW', 'RELAXATION'],
    climateZone: 'MOUNTAIN',
    popularityScore: 8.8,
    description: 'Himalayan haven for adventure seekers — snow peaks, river rafting, and the iconic Rohtang Pass.',
    highlights: ['Rohtang Pass', 'Solang Valley', 'Old Manali', 'Beas River Rafting'],
    imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800',
    costProfile: {
      style: 'BUDGET',
      foodDailyLow: 250, foodDailyMid: 500, foodDailyHigh: 1000,
      localTransitDaily: 300, activitiesDaily: 600,
      hotelNightLow: 600, hotelNightMid: 1500, hotelNightHigh: 4000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '01': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Snow season, road access varies' },
      '02': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Snow activities peak' },
      '03': { weatherScore: 5, crowdLevel: 'LOW', description: 'Transition, some closures' },
      '04': { weatherScore: 7, crowdLevel: 'HIGH', description: 'Rohtang opens, pleasant' },
      '05': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Best weather, apple blossoms' },
      '06': { weatherScore: 8, crowdLevel: 'PEAK', description: 'Peak summer tourist season' },
      '07': { weatherScore: 5, crowdLevel: 'LOW', description: 'Monsoon, landslide risk' },
      '08': { weatherScore: 5, crowdLevel: 'LOW', description: 'Monsoon continues' },
      '09': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Post-monsoon clarity' },
      '10': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Autumn, excellent views' },
      '11': { weatherScore: 6, crowdLevel: 'LOW', description: 'Snow begins, cold' },
      '12': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Snow lovers\' paradise' },
    },
  },
  {
    id: 'jaisalmer_in',
    slug: 'jaisalmer-india',
    city: 'Jaisalmer',
    country: 'India',
    countryCode: 'IN',
    region: 'South Asia',
    lat: 26.9157,
    lng: 70.9083,
    airportCodes: ['JSA'],
    tags: ['CULTURE', 'ADVENTURE', 'RELAXATION'],
    climateZone: 'ARID',
    popularityScore: 8.1,
    description: 'The Golden City — sand dunes, camel safaris, and a magnificent desert fort rising from the Thar.',
    highlights: ['Jaisalmer Fort', 'Sam Sand Dunes', 'Camel Safari', 'Patwon Ki Haveli'],
    imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800',
    costProfile: {
      style: 'BUDGET',
      foodDailyLow: 200, foodDailyMid: 400, foodDailyHigh: 800,
      localTransitDaily: 250, activitiesDaily: 500,
      hotelNightLow: 500, hotelNightMid: 1200, hotelNightHigh: 3500,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '10': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Cooling down, pleasant' },
      '11': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Ideal desert weather' },
      '12': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Peak season, Desert Festival' },
      '01': { weatherScore: 8, crowdLevel: 'PEAK', description: 'Cool nights, brilliant days' },
      '02': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Pleasant and clear' },
      '03': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Warming up' },
      '04': { weatherScore: 5, crowdLevel: 'LOW', description: 'Hot season begins' },
      '05': { weatherScore: 3, crowdLevel: 'LOW', description: 'Very hot, avoid' },
      '06': { weatherScore: 2, crowdLevel: 'LOW', description: 'Extreme heat' },
      '07': { weatherScore: 3, crowdLevel: 'LOW', description: 'Light monsoon' },
      '08': { weatherScore: 4, crowdLevel: 'LOW', description: 'Hot and humid' },
      '09': { weatherScore: 5, crowdLevel: 'LOW', description: 'Cooling slightly' },
    },
  },
  {
    id: 'rishikesh_in',
    slug: 'rishikesh-india',
    city: 'Rishikesh',
    country: 'India',
    countryCode: 'IN',
    region: 'South Asia',
    lat: 30.0869,
    lng: 78.2676,
    airportCodes: ['DED'],
    tags: ['ADVENTURE', 'RELIGIOUS', 'RELAXATION', 'MOUNTAINS'],
    climateZone: 'SUBTROPICAL',
    popularityScore: 8.5,
    description: 'Yoga capital of the world — white-water rafting, ashrams, evening aarti on the Ganges.',
    highlights: ['Laxman Jhula', 'River Rafting', 'Triveni Ghat Aarti', 'Neer Garh Waterfall'],
    imageUrl: 'https://images.unsplash.com/photo-1592283591821-03b2384fffb0?w=800',
    costProfile: {
      style: 'BACKPACKER',
      foodDailyLow: 150, foodDailyMid: 350, foodDailyHigh: 700,
      localTransitDaily: 150, activitiesDaily: 500,
      hotelNightLow: 400, hotelNightMid: 1000, hotelNightHigh: 3000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '09': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Great rafting conditions' },
      '10': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Perfect weather, festivals' },
      '11': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Pleasant cool weather' },
      '12': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Cool, yoga retreats popular' },
      '01': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Cold but clear' },
      '02': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Warming, pleasant' },
      '03': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Excellent weather' },
      '04': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Warm and bright' },
      '05': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Hot, pre-monsoon' },
      '06': { weatherScore: 5, crowdLevel: 'LOW', description: 'Monsoon, river too high for rafting' },
      '07': { weatherScore: 4, crowdLevel: 'LOW', description: 'Heavy monsoon' },
      '08': { weatherScore: 5, crowdLevel: 'LOW', description: 'Monsoon tapering' },
    },
  },
  {
    id: 'varanasi_in',
    slug: 'varanasi-india',
    city: 'Varanasi',
    country: 'India',
    countryCode: 'IN',
    region: 'South Asia',
    lat: 25.3176,
    lng: 82.9739,
    airportCodes: ['VNS'],
    tags: ['RELIGIOUS', 'CULTURE', 'FOOD'],
    climateZone: 'SUBTROPICAL',
    popularityScore: 8.3,
    description: 'One of the world\'s oldest cities — sacred ghats, dawn boat rides, and the timeless Ganga Aarti.',
    highlights: ['Dasaswamedh Ghat', 'Morning Boat Ride', 'Sarnath', 'Kashi Vishwanath Temple'],
    imageUrl: 'https://images.unsplash.com/photo-1567591370762-e3f9da27cd83?w=800',
    costProfile: {
      style: 'BUDGET',
      foodDailyLow: 150, foodDailyMid: 350, foodDailyHigh: 700,
      localTransitDaily: 100, activitiesDaily: 200,
      hotelNightLow: 400, hotelNightMid: 1000, hotelNightHigh: 3000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '10': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Dev Deepawali season' },
      '11': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Pleasant and festive' },
      '12': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Cool fog mornings, atmospheric' },
      '01': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Cold but spiritually vibrant' },
      '02': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Warming, pleasant' },
      '03': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Holi celebrations' },
      '04': { weatherScore: 6, crowdLevel: 'LOW', description: 'Hot season starts' },
      '05': { weatherScore: 4, crowdLevel: 'LOW', description: 'Very hot' },
      '06': { weatherScore: 4, crowdLevel: 'LOW', description: 'Monsoon, ghats flooded' },
      '07': { weatherScore: 5, crowdLevel: 'LOW', description: 'Monsoon' },
      '08': { weatherScore: 5, crowdLevel: 'LOW', description: 'Late monsoon' },
      '09': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Post-monsoon refresh' },
    },
  },
  {
    id: 'darjeeling_in',
    slug: 'darjeeling-india',
    city: 'Darjeeling',
    country: 'India',
    countryCode: 'IN',
    region: 'South Asia',
    lat: 27.0360,
    lng: 88.2627,
    airportCodes: ['GAY'],
    tags: ['MOUNTAINS', 'CULTURE', 'RELAXATION', 'FOOD'],
    climateZone: 'MOUNTAIN',
    popularityScore: 7.9,
    description: 'Queen of the Hills — Kanchenjunga views, tea estates, and the famous toy train.',
    highlights: ['Tiger Hill Sunrise', 'Tea Estate Tour', 'Darjeeling Himalayan Railway', 'Batasia Loop'],
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800',
    costProfile: {
      style: 'BUDGET',
      foodDailyLow: 200, foodDailyMid: 450, foodDailyHigh: 900,
      localTransitDaily: 150, activitiesDaily: 300,
      hotelNightLow: 500, hotelNightMid: 1200, hotelNightHigh: 3500,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '03': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Cherry blossoms, clear views' },
      '04': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Rhododendrons in bloom' },
      '05': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Tea plucking season' },
      '06': { weatherScore: 4, crowdLevel: 'LOW', description: 'Monsoon, cloudy' },
      '07': { weatherScore: 4, crowdLevel: 'LOW', description: 'Heavy rain' },
      '08': { weatherScore: 4, crowdLevel: 'LOW', description: 'Monsoon' },
      '09': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Clearing up, lush green' },
      '10': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Brilliant autumn clarity' },
      '11': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Cool, excellent views' },
      '12': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Cold, misty mornings' },
      '01': { weatherScore: 6, crowdLevel: 'LOW', description: 'Very cold, possible snow' },
      '02': { weatherScore: 7, crowdLevel: 'LOW', description: 'Cold but clear' },
    },
  },

  // ────────── INTERNATIONAL ────────────────────────────────────
  {
    id: 'bangkok_th',
    slug: 'bangkok-thailand',
    city: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    region: 'Southeast Asia',
    lat: 13.7563,
    lng: 100.5018,
    airportCodes: ['BKK', 'DMK'],
    tags: ['NIGHTLIFE', 'FOOD', 'CULTURE', 'SHOPPING', 'BEACH'],
    climateZone: 'TROPICAL',
    popularityScore: 9.5,
    description: 'Asia\'s electric capital — rooftop bars, street food, golden temples and the best nightlife in the region.',
    highlights: ['Grand Palace', 'Chatuchak Market', 'Khao San Road', 'Floating Markets'],
    imageUrl: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
    costProfile: {
      style: 'BUDGET',
      foodDailyLow: 250, foodDailyMid: 600, foodDailyHigh: 1500,
      localTransitDaily: 200, activitiesDaily: 500,
      hotelNightLow: 700, hotelNightMid: 1800, hotelNightHigh: 5000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '11': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Cool and dry, best season' },
      '12': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Perfect weather, peak tourism' },
      '01': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Excellent, slightly crowded' },
      '02': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Great weather' },
      '03': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Getting hot' },
      '04': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Very hot, Songkran festival' },
      '05': { weatherScore: 5, crowdLevel: 'LOW', description: 'Hot and humid, rains start' },
      '06': { weatherScore: 4, crowdLevel: 'LOW', description: 'Wet season' },
      '07': { weatherScore: 4, crowdLevel: 'LOW', description: 'Heavy rain' },
      '08': { weatherScore: 4, crowdLevel: 'LOW', description: 'Monsoon' },
      '09': { weatherScore: 4, crowdLevel: 'LOW', description: 'Wettest month' },
      '10': { weatherScore: 5, crowdLevel: 'LOW', description: 'End of rainy season' },
    },
  },
  {
    id: 'bali_id',
    slug: 'bali-indonesia',
    city: 'Bali',
    country: 'Indonesia',
    countryCode: 'ID',
    region: 'Southeast Asia',
    lat: -8.3405,
    lng: 115.0920,
    airportCodes: ['DPS'],
    tags: ['BEACH', 'CULTURE', 'RELAXATION', 'ADVENTURE', 'FOOD'],
    climateZone: 'TROPICAL',
    popularityScore: 9.6,
    description: 'Island of the Gods — volcanic rice terraces, surf beaches, Hindu temples and world-class wellness.',
    highlights: ['Ubud Rice Terraces', 'Tanah Lot Temple', 'Seminyak Beach', 'Mount Batur Sunrise Hike'],
    imageUrl: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
    costProfile: {
      style: 'BUDGET',
      foodDailyLow: 300, foodDailyMid: 700, foodDailyHigh: 1800,
      localTransitDaily: 250, activitiesDaily: 600,
      hotelNightLow: 800, hotelNightMid: 2500, hotelNightHigh: 8000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '04': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Dry season begins, ideal' },
      '05': { weatherScore: 9, crowdLevel: 'MEDIUM', description: 'Less crowded, great weather' },
      '06': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Peak dry season' },
      '07': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Busiest month, perfect weather' },
      '08': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Peak season continues' },
      '09': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Still dry and warm' },
      '10': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Shoulder season' },
      '11': { weatherScore: 5, crowdLevel: 'LOW', description: 'Wet season begins' },
      '12': { weatherScore: 5, crowdLevel: 'MEDIUM', description: 'Wet but lush and festive' },
      '01': { weatherScore: 4, crowdLevel: 'LOW', description: 'Wettest period' },
      '02': { weatherScore: 4, crowdLevel: 'LOW', description: 'Wet season' },
      '03': { weatherScore: 6, crowdLevel: 'LOW', description: 'Drying out, budget prices' },
    },
  },
  {
    id: 'dubai_ae',
    slug: 'dubai-uae',
    city: 'Dubai',
    country: 'UAE',
    countryCode: 'AE',
    region: 'Middle East',
    lat: 25.2048,
    lng: 55.2708,
    airportCodes: ['DXB', 'DWC'],
    tags: ['SHOPPING', 'LUXURY', 'CULTURE', 'ADVENTURE', 'NIGHTLIFE'],
    climateZone: 'ARID',
    popularityScore: 9.3,
    description: 'Superlative city — tallest buildings, indoor ski slopes, gold souks and desert adventures.',
    highlights: ['Burj Khalifa', 'Dubai Mall', 'Desert Safari', 'Palm Jumeirah'],
    imageUrl: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800',
    costProfile: {
      style: 'COMFORT',
      foodDailyLow: 800, foodDailyMid: 1800, foodDailyHigh: 4000,
      localTransitDaily: 300, activitiesDaily: 1500,
      hotelNightLow: 3000, hotelNightMid: 7000, hotelNightHigh: 20000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '11': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Perfect weather, shopping festival' },
      '12': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Best time, festive atmosphere' },
      '01': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Cool and dry, ideal' },
      '02': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Great weather' },
      '03': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Warming up, still pleasant' },
      '04': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Hot season begins' },
      '05': { weatherScore: 5, crowdLevel: 'LOW', description: 'Very hot' },
      '06': { weatherScore: 3, crowdLevel: 'LOW', description: 'Extreme heat' },
      '07': { weatherScore: 2, crowdLevel: 'LOW', description: 'Hottest month, 45°C+' },
      '08': { weatherScore: 2, crowdLevel: 'LOW', description: 'Extreme heat and humidity' },
      '09': { weatherScore: 4, crowdLevel: 'LOW', description: 'Still very hot' },
      '10': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Cooling down, pleasant' },
    },
  },
  {
    id: 'singapore_sg',
    slug: 'singapore',
    city: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    region: 'Southeast Asia',
    lat: 1.3521,
    lng: 103.8198,
    airportCodes: ['SIN'],
    tags: ['FOOD', 'SHOPPING', 'CULTURE', 'FAMILY', 'NIGHTLIFE'],
    climateZone: 'TROPICAL',
    popularityScore: 9.1,
    description: 'Asia\'s clean, green city-state — Gardens by the Bay, hawker centres, Sentosa and world-class transit.',
    highlights: ['Gardens by the Bay', 'Hawker Centres', 'Sentosa Island', 'Marina Bay Sands'],
    imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800',
    costProfile: {
      style: 'COMFORT',
      foodDailyLow: 500, foodDailyMid: 1200, foodDailyHigh: 3000,
      localTransitDaily: 200, activitiesDaily: 1000,
      hotelNightLow: 2500, hotelNightMid: 6000, hotelNightHigh: 18000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '02': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Driest period, Chinese New Year' },
      '03': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Pleasant and dry' },
      '04': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Warm and slightly wet' },
      '05': { weatherScore: 7, crowdLevel: 'HIGH', description: 'Warm, occasional showers' },
      '06': { weatherScore: 7, crowdLevel: 'HIGH', description: 'Great Singapore Sale period' },
      '07': { weatherScore: 7, crowdLevel: 'HIGH', description: 'School holiday season' },
      '08': { weatherScore: 8, crowdLevel: 'PEAK', description: 'National Day celebrations' },
      '09': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Haze risk from Sumatra' },
      '10': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Wet season starts' },
      '11': { weatherScore: 5, crowdLevel: 'MEDIUM', description: 'Wettest month' },
      '12': { weatherScore: 7, crowdLevel: 'PEAK', description: 'Festive, Formula 1 atmosphere' },
      '01': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Monsoon season' },
    },
  },
  {
    id: 'phuket_th',
    slug: 'phuket-thailand',
    city: 'Phuket',
    country: 'Thailand',
    countryCode: 'TH',
    region: 'Southeast Asia',
    lat: 7.8804,
    lng: 98.3923,
    airportCodes: ['HKT'],
    tags: ['BEACH', 'NIGHTLIFE', 'RELAXATION', 'FOOD', 'ADVENTURE'],
    climateZone: 'TROPICAL',
    popularityScore: 9.0,
    description: 'Thailand\'s largest island — crystal clear Andaman beaches, vibrant nightlife, island-hopping paradise.',
    highlights: ['Phi Phi Islands', 'Patong Beach', 'Big Buddha', 'James Bond Island'],
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
    costProfile: {
      style: 'BUDGET',
      foodDailyLow: 300, foodDailyMid: 700, foodDailyHigh: 1600,
      localTransitDaily: 300, activitiesDaily: 700,
      hotelNightLow: 900, hotelNightMid: 2500, hotelNightHigh: 7000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '11': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Dry season starts, ideal' },
      '12': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Perfect beach weather' },
      '01': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Best month, clear seas' },
      '02': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Excellent, shoulder crowd' },
      '03': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Hot and sunny' },
      '04': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Shoulder season' },
      '05': { weatherScore: 4, crowdLevel: 'LOW', description: 'Wet season begins' },
      '06': { weatherScore: 3, crowdLevel: 'LOW', description: 'Heavy rain, rough seas' },
      '07': { weatherScore: 3, crowdLevel: 'LOW', description: 'Monsoon, sea warnings' },
      '08': { weatherScore: 3, crowdLevel: 'LOW', description: 'Heavy rain' },
      '09': { weatherScore: 3, crowdLevel: 'LOW', description: 'Wettest month, avoid' },
      '10': { weatherScore: 5, crowdLevel: 'LOW', description: 'End of wet season' },
    },
  },
  {
    id: 'kathmandu_np',
    slug: 'kathmandu-nepal',
    city: 'Kathmandu',
    country: 'Nepal',
    countryCode: 'NP',
    region: 'South Asia',
    lat: 27.7172,
    lng: 85.3240,
    airportCodes: ['KTM'],
    tags: ['MOUNTAINS', 'CULTURE', 'ADVENTURE', 'RELIGIOUS'],
    climateZone: 'SUBTROPICAL',
    popularityScore: 8.6,
    description: 'Gateway to the Himalayas — ancient temples, trekking base camps, and the greatest mountains on Earth.',
    highlights: ['Swayambhunath Stupa', 'Pashupatinath Temple', 'Thamel', 'Everest Trekking'],
    imageUrl: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800',
    costProfile: {
      style: 'BACKPACKER',
      foodDailyLow: 150, foodDailyMid: 350, foodDailyHigh: 800,
      localTransitDaily: 100, activitiesDaily: 400,
      hotelNightLow: 400, hotelNightMid: 1200, hotelNightHigh: 3500,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '09': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Pre-trekking season' },
      '10': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Prime trekking, clear Himalayas' },
      '11': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Excellent, slightly cooler' },
      '12': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Cold but clear, fewer tourists' },
      '01': { weatherScore: 5, crowdLevel: 'LOW', description: 'Cold and dry' },
      '02': { weatherScore: 6, crowdLevel: 'LOW', description: 'Cold, warming slowly' },
      '03': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Spring trekking season begins' },
      '04': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Rhododendrons, best spring treks' },
      '05': { weatherScore: 7, crowdLevel: 'HIGH', description: 'Warm, pre-monsoon' },
      '06': { weatherScore: 4, crowdLevel: 'LOW', description: 'Monsoon, leeches on trails' },
      '07': { weatherScore: 3, crowdLevel: 'LOW', description: 'Heavy monsoon' },
      '08': { weatherScore: 4, crowdLevel: 'LOW', description: 'Monsoon continues' },
    },
  },
  {
    id: 'colombo_lk',
    slug: 'colombo-sri-lanka',
    city: 'Colombo',
    country: 'Sri Lanka',
    countryCode: 'LK',
    region: 'South Asia',
    lat: 6.9271,
    lng: 79.8612,
    airportCodes: ['CMB'],
    tags: ['CULTURE', 'BEACH', 'FOOD', 'WILDLIFE', 'RELAXATION'],
    climateZone: 'TROPICAL',
    popularityScore: 8.0,
    description: 'Pearl of the Indian Ocean — ancient ruins, lush tea hills, wild elephants and pristine beaches.',
    highlights: ['Sigiriya Rock', 'Kandy Temple of the Tooth', 'Yala National Park', 'Mirissa Whale Watching'],
    imageUrl: 'https://images.unsplash.com/photo-1562602833-0f4ab2fc46e3?w=800',
    costProfile: {
      style: 'BUDGET',
      foodDailyLow: 200, foodDailyMid: 450, foodDailyHigh: 1000,
      localTransitDaily: 150, activitiesDaily: 400,
      hotelNightLow: 600, hotelNightMid: 1500, hotelNightHigh: 4500,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '12': { weatherScore: 8, crowdLevel: 'HIGH', description: 'West coast dry season' },
      '01': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Excellent beach weather west' },
      '02': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Great for west and central' },
      '03': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Transitional' },
      '04': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Warming, first rains' },
      '05': { weatherScore: 4, crowdLevel: 'LOW', description: 'SW Monsoon, west coast wet' },
      '06': { weatherScore: 4, crowdLevel: 'LOW', description: 'Monsoon peak west' },
      '07': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'East coast dry season' },
      '08': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'East coast ideal' },
      '09': { weatherScore: 6, crowdLevel: 'LOW', description: 'Shoulder season' },
      '10': { weatherScore: 5, crowdLevel: 'LOW', description: 'NE monsoon starts' },
      '11': { weatherScore: 5, crowdLevel: 'LOW', description: 'Wet in east, dry in west' },
    },
  },
  {
    id: 'kuala_lumpur_my',
    slug: 'kuala-lumpur-malaysia',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    region: 'Southeast Asia',
    lat: 3.1390,
    lng: 101.6869,
    airportCodes: ['KUL'],
    tags: ['FOOD', 'SHOPPING', 'CULTURE', 'NIGHTLIFE', 'FAMILY'],
    climateZone: 'TROPICAL',
    popularityScore: 8.7,
    description: 'Petronas Twin Towers, diverse street food, Batu Caves and a vibrant multicultural city.',
    highlights: ['Petronas Twin Towers', 'Batu Caves', 'Jalan Alor Food Street', 'KL Bird Park'],
    imageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800',
    costProfile: {
      style: 'BUDGET',
      foodDailyLow: 250, foodDailyMid: 550, foodDailyHigh: 1200,
      localTransitDaily: 150, activitiesDaily: 400,
      hotelNightLow: 800, hotelNightMid: 2000, hotelNightHigh: 6000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '05': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Drier spell, good to visit' },
      '06': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Less rain, pleasant' },
      '07': { weatherScore: 7, crowdLevel: 'HIGH', description: 'School holidays, busy' },
      '08': { weatherScore: 7, crowdLevel: 'HIGH', description: 'Festival season, Merdeka' },
      '01': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Chinese New Year prep' },
      '02': { weatherScore: 7, crowdLevel: 'HIGH', description: 'Chinese New Year, festive' },
      '03': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Hot, occasional showers' },
      '04': { weatherScore: 5, crowdLevel: 'MEDIUM', description: 'Heavy afternoon rains' },
      '09': { weatherScore: 6, crowdLevel: 'LOW', description: 'Shoulder month' },
      '10': { weatherScore: 5, crowdLevel: 'LOW', description: 'Wetter month' },
      '11': { weatherScore: 5, crowdLevel: 'MEDIUM', description: 'Rainy season' },
      '12': { weatherScore: 6, crowdLevel: 'HIGH', description: 'Year-end festivities' },
    },
  },
  {
    id: 'tokyo_jp',
    slug: 'tokyo-japan',
    city: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    region: 'East Asia',
    lat: 35.6762,
    lng: 139.6503,
    airportCodes: ['NRT', 'HND'],
    tags: ['CULTURE', 'FOOD', 'SHOPPING', 'NIGHTLIFE', 'FAMILY'],
    climateZone: 'TEMPERATE',
    popularityScore: 9.7,
    description: 'Neon-lit Tokyo — ancient temples next to supertall skyscrapers, the world\'s best food scene, and unmatched transit.',
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'teamLab Planets', 'Tsukiji Outer Market'],
    imageUrl: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
    costProfile: {
      style: 'COMFORT',
      foodDailyLow: 700, foodDailyMid: 1500, foodDailyHigh: 3500,
      localTransitDaily: 500, activitiesDaily: 1000,
      hotelNightLow: 2500, hotelNightMid: 6000, hotelNightHigh: 18000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '03': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Cherry blossom season' },
      '04': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Sakura peak, very busy' },
      '05': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Golden Week, warm' },
      '06': { weatherScore: 5, crowdLevel: 'MEDIUM', description: 'Rainy season, humid' },
      '07': { weatherScore: 5, crowdLevel: 'MEDIUM', description: 'Hot and humid' },
      '08': { weatherScore: 5, crowdLevel: 'HIGH', description: 'Summer festivals, hot' },
      '09': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Typhoon risk, cooling' },
      '10': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Autumn colours, ideal' },
      '11': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Koyo (fall foliage) season' },
      '12': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Winter illuminations' },
      '01': { weatherScore: 6, crowdLevel: 'LOW', description: 'Cold but clear, fewer tourists' },
      '02': { weatherScore: 6, crowdLevel: 'LOW', description: 'Cold, less crowded' },
    },
  },
  {
    id: 'paris_fr',
    slug: 'paris-france',
    city: 'Paris',
    country: 'France',
    countryCode: 'FR',
    region: 'Europe',
    lat: 48.8566,
    lng: 2.3522,
    airportCodes: ['CDG', 'ORY'],
    tags: ['CULTURE', 'ROMANTIC', 'FOOD', 'SHOPPING', 'NIGHTLIFE'],
    climateZone: 'TEMPERATE',
    popularityScore: 9.4,
    description: 'The City of Light — Eiffel Tower, world-class art, patisseries, and timeless romantic boulevards.',
    highlights: ['Eiffel Tower', 'Louvre Museum', 'Montmartre', 'Seine River Cruise'],
    imageUrl: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800',
    costProfile: {
      style: 'COMFORT',
      foodDailyLow: 1000, foodDailyMid: 2500, foodDailyHigh: 6000,
      localTransitDaily: 400, activitiesDaily: 1500,
      hotelNightLow: 4000, hotelNightMid: 9000, hotelNightHigh: 25000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '04': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Spring blooms, mild weather' },
      '05': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Lovely and warm' },
      '06': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Long days, vibrant' },
      '07': { weatherScore: 8, crowdLevel: 'PEAK', description: 'Bastille Day, busy' },
      '08': { weatherScore: 8, crowdLevel: 'HIGH', description: 'Hot, Parisians on holiday' },
      '09': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Ideal month, fewer crowds' },
      '10': { weatherScore: 7, crowdLevel: 'MEDIUM', description: 'Autumn colours, pleasant' },
      '11': { weatherScore: 5, crowdLevel: 'LOW', description: 'Cool and overcast' },
      '12': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Christmas markets, magical' },
      '01': { weatherScore: 5, crowdLevel: 'LOW', description: 'Cold, cheap prices' },
      '02': { weatherScore: 5, crowdLevel: 'LOW', description: 'Cold, fashion week' },
      '03': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Early spring warming' },
    },
  },
  {
    id: 'maldives_mv',
    slug: 'maldives',
    city: 'Malé',
    country: 'Maldives',
    countryCode: 'MV',
    region: 'South Asia',
    lat: 4.1755,
    lng: 73.5093,
    airportCodes: ['MLE'],
    tags: ['BEACH', 'RELAXATION', 'ROMANTIC', 'ADVENTURE'],
    climateZone: 'TROPICAL',
    popularityScore: 9.2,
    description: 'Ultimate luxury escape — overwater villas, electric blue lagoons, and pristine coral reefs.',
    highlights: ['Overwater Bungalows', 'Snorkeling & Diving', 'Manta Ray Watching', 'Local Island Stays'],
    imageUrl: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800',
    costProfile: {
      style: 'LUXURY',
      foodDailyLow: 1500, foodDailyMid: 3500, foodDailyHigh: 8000,
      localTransitDaily: 1000, activitiesDaily: 2000,
      hotelNightLow: 8000, hotelNightMid: 20000, hotelNightHigh: 60000,
      currency: 'INR', source: 'INTERNAL_MODEL', validFrom: '2026-01-01',
    },
    seasonProfile: {
      '11': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Dry season starts' },
      '12': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Perfect conditions' },
      '01': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Best weather, peak prices' },
      '02': { weatherScore: 9, crowdLevel: 'PEAK', description: 'Ideal, calm seas' },
      '03': { weatherScore: 9, crowdLevel: 'HIGH', description: 'Great visibility for diving' },
      '04': { weatherScore: 8, crowdLevel: 'MEDIUM', description: 'Transition, good value' },
      '05': { weatherScore: 5, crowdLevel: 'LOW', description: 'Wet season, rough seas' },
      '06': { weatherScore: 4, crowdLevel: 'LOW', description: 'Monsoon, low prices' },
      '07': { weatherScore: 4, crowdLevel: 'LOW', description: 'Rainy but diving possible' },
      '08': { weatherScore: 5, crowdLevel: 'LOW', description: 'Wet season continues' },
      '09': { weatherScore: 5, crowdLevel: 'LOW', description: 'Transitional' },
      '10': { weatherScore: 6, crowdLevel: 'MEDIUM', description: 'Improving conditions' },
    },
  },
];

// ── Lookup helpers ────────────────────────────────────────────

export function getDestinationBySlug(slug: string): Destination | undefined {
  return DESTINATIONS.find(d => d.slug === slug);
}

// Accept slugs as well as a city or country typed into the destination field.
// This prevents an unknown/alternate label from silently falling back to Goa.
export function findDestination(value: string): Destination | undefined {
  const query = decodeURIComponent(value || '').trim().toLowerCase();
  if (!query) return undefined;

  return DESTINATIONS.find((destination) =>
    destination.slug.toLowerCase() === query ||
    destination.id.toLowerCase() === query ||
    destination.city.toLowerCase() === query ||
    destination.country.toLowerCase() === query ||
    `${destination.city}, ${destination.country}`.toLowerCase() === query
  );
}

export function getDestinationById(id: string): Destination | undefined {
  return DESTINATIONS.find(d => d.id === id);
}

export function getDomesticDestinations(): Destination[] {
  return DESTINATIONS.filter(d => d.countryCode === 'IN');
}

export function getInternationalDestinations(): Destination[] {
  return DESTINATIONS.filter(d => d.countryCode !== 'IN');
}

export function getWeatherScore(destination: Destination, month: string): number {
  return destination.seasonProfile[month]?.weatherScore ?? 5;
}

export function getCrowdLevel(destination: Destination, month: string): string {
  return destination.seasonProfile[month]?.crowdLevel ?? 'MEDIUM';
}
